### ISSUE TITLE
Migrate from netaddr to ipaddress library

### ISSUE THREAD

**Issue by iamtmehdi** [jathanism/cidrize#13]
Firstly thanks for creating this module.

I'd like to recommend looking into migrating your code using the netaddr to ipaddress library. netaddr is deprecated after Python 3.5+, and ipaddress contains the functionality that netaddr has.

From netaddr Github:
> A system-independent network address manipulation library for Python 2.7 and 3.5+. (Python 2.7 and 3.5 support is deprecated)

**Comment by jathanism** [comment]
I believe you may have misread this. They are dropping support for Python version less than 3.5!

Besides, `netaddr` is superior to `ipaddress` in many ways and the library would have to be completely rewritten around `ipaddress`! Thank you for the suggestion but I don't think there is any need.
