### ISSUE TITLE
Python 3 compatability

### ISSUE THREAD

**Issue by crutchcorn** [jathanism/cidrize#6]
Hi! I'm hoping that I can use your library in a project I'm working on! I am able and willing to convert this to a Python 3 version. I would also like to add network mask and host mask notation, but I'm not overly familiar with Python 2 code. I know, however, that there are ways to do Python 2 and 3 compatable code, and that's something that I could do while porting to Python 3.

I want to make sure that this is something that we could agree on and get together as one codebase. Thoughts on the matter?

**Comment by jathanism** [comment]
Fixed in #9
