### ISSUE TITLE
Corrected cidrize.py to work with Python 3

### ISSUE THREAD

**Issue by jemcgrath1** [jathanism/cidrize#7]
Hi,

Please be advised that if you visit my github page https://github.com/jemcgrath1/cidrize
I have updated the cidrize.py file to now work with Python 3.X.

Please feel free to take this file and remerge with the original project.

Thanks.

**Comment by jathanism** [comment]
Oof well 3 years later, we have python 3 support officially merged in. Thanks for letting me know even tho I wasn't paying attention! 

Fixed in #9
