### ISSUE TITLE
invalid IPNetwork error

### ISSUE THREAD

**Issue by InfoSecured** [jathanism/cidrize#8]
Hi,

I'm new to your script but by the looks of it, it should do exactly what I'm looking to do. I have a long list of IP addresses in two different formats:

1. A normal formatted IP address (ex. 192.168.1.20)
2. An IP range 192.168.1.20-192.168.1.30

When parsing through the list, I seem to get an error right away with a regular IP address.

`Traceback (most recent call last):
  File ".\TenableCurrentIPsScanned.py", line 130, in <module>
    searchableList = cleanIPs(ipList)
  File ".\TenableCurrentIPsScanned.py", line 122, in cleanIPs
    cidrize(ipAddress)
  File "C:\Program Files\Python27\lib\site-packages\cidrize.py", line 328, in cidrize
    raise CidrizeError(err)
cidrize.CidrizeError: invalid IPNetwork "10.90.79.38"`

Any thoughts on why?

**Comment by jathanism** [comment]
It's 2.5 years later, but maybe this can be of some help? :)

```
In [7]: cidrize.cidrize("10.90.79.38")
Out[7]: [IPNetwork('10.90.79.38/32')]
```

¯\\\_(ツ)\_/¯
